app:
  message: Hello from DEV environment

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: ONBOARDING_DIT
    password: ONBOARDING_DIT
    driver-class-name: oracle.jdbc.OracleDriver
  redis:
    host: localhost
    port: 6379
